spring:
  datasource:
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none   # Flyway handles schema
    show-sql: true
  flyway:
    enabled: true
  h2:
    console:
      enabled: false